# .github/workflows/ci-cd.yml
name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract version from package.json
      run: |
        VERSION=$(jq -r .version package.json)
        echo "VERSION=$VERSION" > .env

    - name: Commit updated .env
      run: |
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .env
        git commit -m "chore: update .env with version $VERSION"
        git push

    - name: Build and push image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/hello-ci-cd:${{ env.VERSION }}
        
    - name: Trigger Portainer Webhook
      run: curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}
